---
- name: Create directory
  file: path={{ item }} state=directory
  with_items:
    - "mongo_image/"

- name: Docker build image for shard and config
  command: docker build --force-rm -f mongod/Dockerfile_{{ item.replica_name }} -t {{ item.replica_name }}:{{ version }} mongod/
  with_items:
    - "{{ replica_set }}"
  register: replica_result

- name: Docker build image for router
  command: docker build --force-rm -f mongos/Dockerfile_{{ router_set.name }} -t {{ router_set.name }}:{{ version }} mongos/
  register: router_result

- name: Save shard and config image # docker load --input ubuntu_14.04.tar
  command: docker save -o mongo_image/{{ item.replica_name }}.tar {{ item.replica_name }}:{{ version }}
  with_items:
    - "{{ replica_set }}"
  when: replica_result is succeeded

- name: Save router image
  command: docker save -o mongo_image/{{ router_set.name }}.tar {{ router_set.name }}:{{ version }} 
  when: replica_result is succeeded

- name: Remove directory
  file: path={{ item }} state=absent
  with_items:
    - "mongod/"
    - "mongos/"
