---
- name: Create directory
  file: path={{ item }} state=directory mode=0777
  with_items:
    - "mongod/files/"
    - "mongoc/files/"
    - "mongos/files/"

- name: Render replicat_set config 
  template: 
    src: replica.js.j2
    dest: "testfolder/{{ item.0.name }}-{{ item.1 }}.js"
  with_subelements:
    - "{{ hosts_set }}"
    - ip