---
- name: Import the public key used by the package management system
  command: apt-key adv --keyserver hkp://keyserver.ubuntu.com:80 --recv 0C49F3730359A14518585931BC711F9BA15703C6
  become: yes

- name: Create a list file for MongoDB
  shell: echo "deb [ arch=amd64,arm64 ] http://repo.mongodb.org/apt/ubuntu xenial/mongodb-org/3.4 multiverse" | tee /etc/apt/sources.list.d/mongodb-org-3.4.list
  become: yes

- name: Reload local package database and install the MongoDB packages.
  apt:
    name: mongodb-org
    update_cache: yes
  become: yes
