---
- name: Create root user for MongoDB 
  mongodb_user:
    database: admin
    login_port: "{{ port }}"
    name: "{{ mongodb_admin_user }}"
    password: "{{ mongodb_admin_password }}"
    roles:
      - { db: "admin", role: "userAdminAnyDatabase" }
      - { db: "admin", role: "root" }
    state: present
  when: is_master

# - name: Create MongoDB root user siteRootAdmin
#   mongodb_user:
#     login_port: "27017"
#     database: "admin"
#     name: "{{ mongodb_admin_user }}"
#     password: "{{ mongodb_admin_password }}"
#     roles: "root"

# - name: Create MongoDB administrative user siteUserAdmin
#   mongodb_user:
#     login_user: "{{ mongodb_admin_user }}"
#     login_password: "{{ mongodb_admin_password }}"
#     login_port: "27017"
#     database: "e-gov"
#     name: "{{ mongodb_user }}"
#     password: "{{ mongodb_password }}"
#     roles:
#       - { db: "admin", role: "readWrite" }
#       - { db: "{{ mongodb_database }}", role: "readWrite" }

