---
- name: Install mongo
  hosts: all
  roles:
   - role: common

- name: Config Replica
  hosts: replica
  roles:
   - role: replica

- name: Init Replica
  hosts: replica
  roles:
   - role: replica_up