---
- name: Install mongo
  hosts: mongo
  roles:
   - role: common

- name: RS_SAAA -- Replica
  vars:
    rs_conf: "{{ replica_sa }}"
  hosts: replica_sa
  roles:
   - role: replica

- name: RS_SBBB -- Replica
  vars:
    rs_conf: "{{ replica_sb }}"
  hosts: replica_sb
  roles:
   - role: replica

- name: RS_SAAA -- Replica UP
  vars:
    rs_conf: "{{ replica_sa }}"
    rs_server_config: []
  hosts: replica_sa
  roles:
   - role: replica_up

- name: RS_SBBB -- Replica UP
  vars:
    rs_conf: "{{ replica_sb }}"
    rs_server_config: []
  hosts: replica_sb
  roles:
   - role: replica_up

- name: local test use
  vars:
    rs_conf: "{{ replica_sa }}"
  gather_facts: true
  hosts: localserver
  roles:
   - role: localtest

# - name: local test use 2
#   vars:
#     rs_conf: "{{ replica_sb }}"
#   gather_facts: true
#   hosts: localserver
#   roles:
#    - role: localtest
