---
# - name: Install mongo
#   hosts: mongo
#   roles:
#    - role: common

- name: Config Replica and Init Replica
  hosts: replica
  roles:
   - role: replica
   - role: replica_up

# - name: Init Replica
#   hosts: replica
#   roles:
#    - role: replica_up

- name: local test use
  hosts: localserver
  roles:
   - role: localtest