---
- name: Install mongo
  hosts: mongo
  roles:
   - role: common

- name: RS_SAAA -- Replica
  vars:
    rs_conf: "{{ replica_sa }}"
  hosts: replica_sa
  roles:
   - role: replica_build
   - role: replica_up

- name: RS_SBBB -- Replica
  vars:
    rs_conf: "{{ replica_sb }}"
  hosts: replica_sb
  roles:
   - role: replica_build
   - role: replica_up

- name: RS_CONFIG
  vars:
    rs_conf: "{{ replica_ca }}"
  hosts: configs
  roles:
   - role: replica_build
   - role: replica_up

- name: ROUTER
  vars:
    rs_conf: "{{ router_set }}"
  hosts: routers
  roles:
   - role: router_build

- name: local test use
  vars:
    rs_conf: "{{ router_set }}"
  gather_facts: true
  hosts: localserver
  roles:
   - role: localtest

