# all:
#   children:
localserver:
  hosts:
    localrun: 
      ansible_connection: local
      replica_name: "replica_sa"
mongo:
  hosts:
    atom1:
      ansible_ssh_host: 192.168.33.10
    atom2:
      ansible_ssh_host: 192.168.33.11
  vars:
    ansible_ssh_port: 22 
    ansible_ssh_private_key_file: ~/.vagrant.d/insecure_private_key
    ansible_user: vagrant
  children:
    replica:
      children:
        replica_sa:
          hosts:
            atom1:
              set_config: true
            atom2:
              set_config: false
          vars:
            db_name: "test"
            db_path: "/data/db/rs-a"
            replica_name: "replica_sa"
            domain: "0.0.0.0"
            port: 27018
            cluster_role: "shardsvr"
        replica_sb:
          hosts:
            atom1:
              set_config: true
            atom2:
              set_config: false
          vars:
            db_name: "test"
            db_path: "/data/db/rs-b"
            replica_name: "replica_sb"
            domain: "0.0.0.0"
            port: 27019
            cluster_role: "shardsvr"