# all:
#   children:
localserver:
  hosts:
    localrun: 
      ansible_connection: local
      replica_name: "replica_sa"
mongo:
  hosts:
    atom1:
      ansible_ssh_host: 192.168.33.10
      set_config: true
    atom2:
      ansible_ssh_host: 192.168.33.11
  vars:
    set_config: false
    ansible_ssh_port: 22 
    ansible_ssh_private_key_file: ~/.vagrant.d/insecure_private_key
    ansible_user: vagrant
  children:
    replica:
      children:
        replica_sa:
          hosts:
            atom1:
            atom2:
        replica_sb:
          hosts:
            atom1:
            atom2: