# -*- mode: ruby -*-
# vi: set ft=ruby :

# Vagrantfile API/syntax version. Don't touch unless you know what you're doing!
VAGRANTFILE_API_VERSION = "2"

# <ubuntu/trusty64|bento/ubuntu-16.04
OS_IMAGE = "bento/ubuntu-16.04"

Vagrant.configure(VAGRANTFILE_API_VERSION) do |config|
  # Use the same key for each machine
  config.ssh.insert_key = false
  N = 2

  (1..N).each do |node_id|
    nid = (node_id - 1)

    config.vm.define "mongodb#{nid}" do |mongodb|
      # https://atlas.hashicorp.com/ubuntu/
      mongodb.vm.hostname = "mongodb#{nid}"
      mongodb.vm.box = OS_IMAGE
      mongodb.vm.network "private_network", ip: "192.168.33.#{10 + nid}"
      mongodb.ssh.forward_agent = true
      
      mongodb.vm.provider "virtualbox" do |vb|
        vb.memory = 1024
        vb.cpus = 1
      end
    end
  end
