all:
  hosts:
    localrun: 
      ansible_connection: local
    atom1:
      ansible_ssh_host: 192.168.33.10
    atom2:
      ansible_ssh_host: 192.168.33.11
  children:
    docker_go:
      hosts:
        atom1:
        atom2:
    localserver:
      hosts:
        localrun:
    mongo:
      hosts:
        atom1:
        atom2:
      vars:
        ansible_ssh_port: 22 
        ansible_ssh_private_key_file: ~/.vagrant.d/insecure_private_key
        ansible_user: vagrant
      children:
        shards:
          children:
            replica_sa:
              hosts:
                atom1_local:
                  docker_host: atom1
                atom2_local:
                  docker_host: atom2
            replica_sb:
              hosts:
                atom1_local:
                  docker_host: atom1
                atom2_local:
                  docker_host: atom2
        config:
          hosts:
            atom1_local:
              docker_host: atom1
            atom2_local:
              docker_host: atom2
        router:
          hosts:
            atom1_local:
              docker_host: atom1