all:
  hosts:
    localrun: 
      ansible_connection: local
    atom1:
      ansible_ssh_host: 192.168.33.10
    atom2:
      ansible_ssh_host: 192.168.33.11
  children:
    docker_go:
      hosts:
        atom1:
        atom2:
      vars:
        ansible_ssh_port: 22 
        ansible_ssh_private_key_file: ~/.vagrant.d/insecure_private_key
        ansible_user: vagrant
    localserver:
      hosts:
        localrun:
    mongo:
      hosts:
        atom1_local:
          ansible_connection: local
          ansible_python_interpreter: /usr/local/bin/python
          docker_host: atom1
          run_script:
            - "replica_sa"
            - "replica_config"
            - "router"
        atom2_local:
          ansible_connection: local
          ansible_python_interpreter: /usr/local/bin/python
          docker_host: atom2
          run_script:
            - "replica_sb"
      children:
        shards:
          children:
            replica_sa:
              hosts:
                atom1_local:
                atom2_local:
            replica_sb:
              hosts:
                atom1_local:
                atom2_local:
        replica_config:
          hosts:
            atom1_local:
            atom2_local:
        router:
          hosts:
            atom1_local:
