---
- name: Create directory
  file: path={{ item }} state=directory mode=0777
  with_items:
    - "{{ ansible_env.HOME }}/opt/confile/mongodb/"
    - "{{ db_path }}"
  become: yes

- name: Copy key file for mongo
  copy: src=files/{{ item.src }} dest={{ ansible_env.HOME }}/opt/confile/{{ item.name }} mode={{ item.mode }}
  with_items:
    - { src: mongo-keyfile, name: mongo-keyfile , mode: "0600" }

- name: Set varible for disable auth
  set_fact: 
    enable_service: false

- name: Render mongo replicat_set config 
  template: 
    src: mongod.conf.j2
    dest: "{{ ansible_env.HOME }}/opt/confile/mongod-{{ replica_name }}.conf"

- name: Start replica set for MongoDB to set user
  command: mongod --config  {{ ansible_env.HOME }}/opt/confile/mongod-{{ replica_name }}.conf
  notify: render config for security replica_set

- name: Set varible to enable auth
  set_fact: 
    enable_service: true


# - name: Restart replica set for MongoDB 
#   command: mongod --config  /opt/confile/mongod-{{ replica_name }}.conf
#   become: yes
  # notify: set role for server 

# - name: Create soft link for mongoDB
#   file: src=/opt/confile/mongod.conf dest=/etc/mongod.conf state=link
#   become: yes
