---
- name: Get server from configure
  set_fact:
    now_item: "{{ item }}"
  with_dict: "{{ rs_conf }}"
  when: inventory_hostname == item.key

- debug: "var=now_item"

- name: Create directory
  file: path={{ item }} state=directory mode=0777
  with_items:
    - "{{ ansible_env.HOME }}/opt/confile/mongodb/"
    - "{{ now_item.value.db_path }}"
  become: yes

- name: Copy key file for mongo
  copy: src=files/{{ item.src }} dest={{ ansible_env.HOME }}/opt/confile/{{ item.name }} mode={{ item.mode }}
  with_items:
    - { src: mongo-keyfile, name: mongo-keyfile , mode: "0600" }

- name: Copy mongoc.js to set slave ok
  copy: src=files/{{ item.src }} dest=/etc/{{ item.name }}
  with_items:
    - { src: mongorc.js, name: mongorc.js }
  become: yes
  when: now_item.value.cluster_role == "configsvr"

- name: Render mongo replicat_set config 
  template: 
    src: mongod.conf.j2
    dest: "{{ ansible_env.HOME }}/opt/confile/mongod-{{ now_item.value.replica_name }}.conf"

- name: Start replica set
  command: mongod --config  {{ ansible_env.HOME }}/opt/confile/mongod-{{ now_item.value.replica_name }}.conf


