FROM {{ mongo_img }}

RUN mkdir -p {{ file_folder }}/mongodb/ 
COPY files/mongo-keyfile {{ file_folder }}/
COPY files/router.js {{ file_folder }}/
COPY files/mongos-{{ item.name }}.conf /etc/mongo/mongos.conf
RUN chown -R 999 {{ file_folder }}/
EXPOSE {{ item.port }}
